### ISSUE TITLE
Config for disable plugin in components without decorators

### ISSUE THREAD

**Issue by matepaiva** [runem/ts-lit-plugin#13]
What a wonderful job you are doing here! This idea is amazing, and it was the main feature I was missing as I came from a React background. Description and import checks are LOVE. Thank you guys very much.

Please correct me if I am wrong, but what I understand is that this plugin will not work well with lit-elements without decorators. Am I right? So, if I use a `<my-button>` element that has a property `message` declared with `static get properties()`, the linter will scream if I try to use `<my button message="message">`:

```js
// my-button.js
import { LitElement, html } from 'lit-element';

class MyButton extends LitElement {
  constructor() {
    super();

    this.message = '';
  }

  static get properties() {
    return {
      message: { type: String },
    };
  }

  render() {
    return html`
      <button>${this.message}</button>
    `;
  }
}
// Register the element with the browser
customElements.define('my-button', MyButton);
```

```js
// my-app.js

import { LitElement, html } from 'lit-element';
import "./my-button";

export class MyApp extends LitElement {
  render() {
    return html`<my-button message="adasda"></my-button>`;
<!--                       |-------- This will scream 'Unkown atribute "message"' -->
  }
}

customElements.define('my-app', MyApp);
```

Am I doing something wrong? If not, is there any way to not check attributes in case that a lit-element has no property decorator? A lot of times we use third-party components and in that case, we can't control if the class will have a decorator or not.

Thank you guys, again. You are amazing.

**Comment by runem** [comment]
Hi @matepaiva, thanks for reporting this issue :-)

Right now I'm working on improving the component parser to include `static get properties()` as well as better parsing overall. The new parser will be much more robust and can detect `properties`, `attributes`, `methods`, `events`, `slots` and `css custom properties` :tada:

You can expect an update to land this week or next week. In the meantime you can whitelist attribute using the `globalHtmlAttributes` setting. Sorry for the inconvenience.

I'll keep you updated!

**Comment by runem** [comment]
https://github.com/runem/ts-lit-plugin/issues/10

**Comment by matepaiva** [comment]
Great news! And is there any way I could help improve it?

**Comment by runem** [comment]
@matepaiva I just published a CLI called [web-component-analyzer](https://github.com/runem/web-component-analyzer) which will be used as the underlying web component analyzer for this plugin. 

It would be really helpful if you can validate that your components are analyzed correctly when using that CLI :-)

```bash
$ npm install -g web-component-analyzer

$ wca analyze my-button.js
```

**Comment by runem** [comment]
The newest versions of both `ts-lit-plugin` and `vscode-lit-plugin` now support `static get properties` by using [web-component-analyzer](https://github.com/runem/web-component-analyzer)  🎉
