### ISSUE TITLE
Support await import when detecting available components

### ISSUE THREAD

**Issue by runem** [runem/ts-lit-plugin#14]
Right now this plugin doesn't detect components used by `await import`. This should be changed to have the same effect as a normal "import" statement so that any `await import` in the file makes the components imported available in the entire file.

<img width="265" alt="Screenshot 2019-03-11 at 14 07 57" src="https://user-images.githubusercontent.com/5372940/54126216-57cca500-4407-11e9-9980-eb0257d118d0.png">

**Comment by runem** [comment]
This feature has been shipped with the newest version of this plugin :tada:

**Comment by abdonrd** [comment]
@runem one recommendation!

Publish the releases on GitHub: https://github.com/runem/ts-lit-plugin/releases
That way, those of us who are listening to the repository see a notification. 🙂

**Comment by runem** [comment]
Thanks for the tip! I'll make sure to publish releases in the future :-)

**Comment by abdonrd** [comment]
@runem happy to help! :)
And you can publish current tags: https://github.com/runem/ts-lit-plugin/releases/edit/v1.0.0
