### ISSUE TITLE
Support for 'playsinline' on HTMLVideoElement

### ISSUE THREAD

**Issue by wessberg** [runem/ts-lit-plugin#9]
The [HTML Specification](https://html.spec.whatwg.org/multipage/media.html#attr-video-playsinline) states:

> The playsinline attribute is a boolean attribute. If present, it serves as a hint to the user agent that the video ought to be displayed "inline" in the document by default, constrained to the element's playback area, instead of being displayed fullscreen or in an independent resizable window.

It would be awesome if ts-lit-plugin supported it.

<img width="502" alt="screen shot 2019-02-18 at 3 02 58 pm" src="https://user-images.githubusercontent.com/20454213/52955984-5838c980-338e-11e9-8924-4c36aafb0ba7.png">

**Comment by runem** [comment]
Thanks for the issue. I will add this missing attribute ASAP 👍

**Comment by runem** [comment]
The newest version of this plugin includes the `playsinline` attribute on the `video` html tag :tada:

**Comment by wessberg** [comment]
Thanks so much! 🔥🔥
